config/routes.rb
Rails.application.routes.draw do
  resources :jobs

end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.page(params[:page]).per(5)
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :job_type, :occupation, :company_name, :location, :url, :description, :apply_information, :deadline, :user_id, :deadline_forever)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<div class="form">
<%= simple_form_for (@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= f.input :title ,label:"Job Title" %>
    
    <%= f.input :company_name ,label:"Company Name" %>
    
    <%= f.input :url ,label:"URL" %>
    
    <%= f.label :job_type %></br>
    <%= f.collection_radio_buttons :job_type, [['full_time', 'Full-time'] ,['part_time', 'Part-time'],['contract ', 'Contract'],['internship ', 'Internship'],['other', 'Other']], :first, :last %>
  	</br>
  	<%= f.label :occupation %><br/>
    <%= f.collection_radio_buttons :occupation, [['web_back_end', 'Web back-end'] ,['web_front-end', 'Web front-end'],['web_design ', 'Web-design'],['qa_testing  ', 'QA/Testing '],['other', 'Other']], :first, :last %>
  	
  	
	  <%= f.input :location ,label:"Location" %>
	  
	  <%= f.input :description ,label:"Description" %>

	  <%= f.input :apply_information ,label:"Apply Information" %>
	  
	  <%= f.label :deadline %></br>
	  <%= f.date_select :deadline ,label:"Deadline", control_col: "col-sm-2" %>
	

	</div>


  <div class="actions">
    <%= f.submit "新增/更新" ,class:'btn btn-success btn-lg'%>
  </div>
<% end %>
</div>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job ,class:'btn btn-default btn-lg'%> | <%= link_to 'Back', jobs_path ,class:'btn btn-default btn-lg'%>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Jobs</h1>

  <table class="table table-hover">
      <thead>
  	<tr>
  		<th><%= t("job.posted") %></th>
  		<th><%= t("job.title") %></th>
  		<th><%= t("job.company_name") %></th>
  		<th><%= t("job.location") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.created_at.to_date %></td>
  			<td><%= link_to job.title, job_path(job) %></td>
  			<td><%= job.company_name %></td>
  			<td><%= job.location %></td>
        <td><%= link_to 'Show', job ,class:'btn btn-default'%></td>
        <td><%= link_to 'Edit', edit_job_path(job) ,class:'btn btn-warning'%></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } ,class:'btn btn-danger'%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @jobs ,:theme => 'twitter-bootstrap-3'  %>
<br>

<%= link_to 'New Job', new_job_path ,class:'btn btn-success btn-lg'%>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path ,class:'btn btn-default btn-lg'%>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Show Jobs</h1>
<table class="table table-hover">
      <thead>
  	<tr>
  		<th>Job Title</th>
  		<th>Company Name</th>
  		<th>URL</th>
  		<th>Job Type</th>
      <th>Occupation</th>
      <th>Location</th>
      <th>Description</th>
      <th>Apply Information</th>
      <th>Deadline</th>
    </tr>
  </thead>
  <tbody>
    <tr>
        <td><%= @job.title %></td>
  		<td><%= @job.company_name %></td>
  		<td><%= @job.url %></td>
  		<td><%= @job.job_type %></td>
  		<td><%= @job.occupation %></td>
  		<td><%= @job.location %></td>
        <td><%= @job.description %></td>
        <td><%= @job.apply_information %></td>
        <td><%= @job.deadline %></td>
      </tr>
    </tbody>
</table>


<%= link_to 'Edit', edit_job_path(@job) ,class:'btn btn-warning btn-lg'%> |
<%= link_to 'Back', jobs_path ,class:'btn btn-default btn-lg'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Job0326</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= yield %>
</div>

</body>
</html>